FROM node:alpine3.18 as builder

WORKDIR /data

COPY .. .

RUN npm i

RUN npm run build


FROM nginx:1.25-alpine3.18

WORKDIR /var/www/app

COPY --from=builder /data/build /var/www/app
COPY /_docker/default.conf /etc/nginx/conf.d/default.conf